name: Deploy Content to 20260415-loganaworkspace [6b5f78ad-c2bd-4c29-a43b-e0a7b3e086f2]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-6b5f78ad-c2bd-4c29-a43b-e0a7b3e086f2.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-6b5f78ad-c2bd-4c29-a43b-e0a7b3e086f2.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: '20260109'
      workspaceName: '20260415-loganaworkspace'
      workspaceId: '492907a5-05cc-4910-92d8-dc6ed869c2c0'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule,HuntingQuery,Parser,Playbook,Workbook,Watchlist'
      branch: 'main'
      sourceControlId: '6b5f78ad-c2bd-4c29-a43b-e0a7b3e086f2'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_6b5f78adc2bd4c29a43be0a7b3e086f2 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-6b5f78ad-c2bd-4c29-a43b-e0a7b3e086f2.ps1